name: StraightUpEconomy
version: ${project.version}
main: com.wasted_ticks.straightupeconomy.StraightUpEconomy
api-version: 1.13
authors: [wasted_ticks]
load: STARTUP
loadbefore: [Vault]
commands:
  balance:
    description: View your balance
    usage: /<command>
  deposit:
    description: Deposit lapis into your account
    usage: /<command> [amount]
  transfer:
    description: Transfer lapis from your account to another account
    usage: /<command> [player] [amount]
  withdraw:
    description: Withdraw lapis from your account
    usage: /<command> [amount]