name: StraightUpEconomy
version: ${project.version}
main: com.wasted_ticks.straightupeconomy.StraightUpEconomy
api-version: 1.13
authors: [wasted_ticks]
load: STARTUP
loadbefore: [Vault]
commands:
  balance:
    description: view balance
    usage: /<command>
  deposit:
    description: deposit gold
    usage: /<command> [amount]
  withdraw:
    description: withdraw gold
    usage: /<command> [amount]